### PR TITLE
make the displayed notice view responds to scroll if it's inside a scroll view

### PR DESCRIPTION
**Pull request by jun1st**
if display the notice view inside a scrollview, make notice view
responds to scroll, so it will keep stay at the top when scrolling

### CODE REVIEW

**Comment by jun1st** [comment]
There is a big bug in these codes, and needs to be fixed,  so please ignore the pull request or wait for sometime.

set the noticeView as the delegate of the parent scrollView will mess up the behavior of original delegate of the scrollView if it has one.  need to add noticeView as a listener, to be notified when scrolled,  instead of being the delegate

**Comment by plu** [comment]
I'm currently struggling with the same wish: Make the `NoticeView` stick on top of my table view while the user is scrolling. Instead of making the `NoticeView` handle it correctly, a much simpler solution is to add the `NoticeView` to another view that is not the `UIScrollView`: Just add it to `self.view.superview` instead of `self.view` (which is supposed to be a `UIScrollView`). Maybe this helps you too :).

``` objc
WBSuccessNoticeView *notice;
notice = [WBSuccessNoticeView successNoticeInView:self.view.superview
                                            title:@"You're offline, will submit later."];
[NSOperationQueue addNoticeView:notice filterDuplicates:YES];
```

**Comment by tciuro** [comment]
@jun1st and @plu,

Is this issue solved now? Unfortunately I cannot find the time to verify this at the moment. Is it still an issue? Thanks for the help!

**Comment by plu** [comment]
@tciuro as @jun1st has noticed himself, just hijacking and resetting the `UIScrollView` delegate isn't an option. There might have been a delegate set already, and if you just reset that, you're most probably going to break something. Another pull request (#41) trying to implement the same feature using `KVO` - I guess @jun1st meant that by "add noticeView as a listener". I'd just close this one.

**Comment by jun1st** [comment]
@tciuro please close this one.  KVO solution @Frugghi provided in another pull request works well and very simple.

**Pull request closed without merging**
