### PR TITLE
Added KVO for UIScrollView contentOffset

### PR DESCRIPTION
**Pull request by Frugghi**
If you add a noticeView to a scrollView you can use KVO to detect user's scroll and move the view.

<del>Example:</del>

<pre><code><del>notice = [WBSuccessNoticeView successNoticeInView:self.view title:@"Test"];
[notice setOriginY:self.tableView.contentOffset.y];
__weak WBNoticeView *noticePointer = notice;
[self.tableView addObserver:notice forKeyPath:@"contentOffset" options:NSKeyValueObservingOptionNew context:NULL];
[notice setDismissalBlock:^(BOOL dismissedInteractively) {
[self.tableView removeObserver:noticePointer forKeyPath:@"contentOffset"];
notice.view = nil;
}];
[notice show];</del></code></pre>

### CODE REVIEW

**Comment by tciuro** [comment]
Hi Tommaso,

I have merged #30, which looks like it would solve the issue you reported: https://github.com/tciuro/NoticeView/pull/30

Could you please pull from master and see if it works for you?

Thanks!

**Comment by Frugghi** [comment]
Hi,

#30 only solve the issue when the notice appear; if you scroll the scrollview while the notice is on the screen it doesn't update its position.

**Comment by jun1st** [comment]
@Frugghi, I've found a way fixing it. but needs to verify and test, going to kick a pull request soon

**Comment by Frugghi** [comment]
@jun1st my solution fix that problem.

**Comment by Frugghi** [comment]
Now you don't need to manually add the observer.

Example:

<pre><code>notice = [WBSuccessNoticeView successNoticeInView:self.view title:@"Test"];
[notice show];</code></pre>

**Comment by jun1st** [comment]
@Frugghi, nice work man! Simple and Clean

**Comment by tciuro** [comment]
@Frugghi, could you please submit another pull request? It seems that your submission cannot be merged automatically. I'd like to do that to credit your work ;-)

**Pull request closed without merging**
