### PR TITLE
Refactor NoticeView for Simplicity & Extensibility, Add Podspec, and Improve Compatibility with Accessibility Labels (Testing)

### PR DESCRIPTION
**Pull request by blakewatters**
Hi there -

I have recently been working with the NoticeView class because it provided such a nice drop-in solution for presenting nicely styled UIAlertView replacements. Thanks for providing such a nice implementation!

I've made several changes in my fork that I think may be of interest in the main distribution so I thought I'd bundle them up for sharing. I am happy to split these commits apart or make further changes to help in getting the changes merged upstream -- just let me know.

This pull request consists of 3 commits:
1. Adds a .podspec file to the repository. I installed via `:local` from a submodule, so I needed a Podspec. I recommend keeping one in the main repository.
2. Updated the internals of `WBNoticeView` to set up accessibility labels and attributes for the notice. I do extensive functional testing with KIF and these changes make it easy to target the notice views inside of tests.
3. The final commit is big and substantive. Today my designer delivered specifications for customizing the display of the notice views to better match our application. After diving into the implementation details of each notice, it became clear that it was going to be very difficult to customize the look and feel given the current structure of the notice classes. I spent several hours this evening refactoring things and I think its much cleaner and lends itself to better re-use. I may have further commits iterating on this tomorrow when I finish out the styling.

There's some breaking API changes in here, but I think its probably worth it and won't be very painful given the small footprint of the library.

There is one other change that I would propose making in the `WBNoticeView` interface: the names of the `delay` and `duration` properties were misleading to me and I had to refer back to the code several times today to keep them straight. I would propose renaming them to `animationDuration` and `timeoutInterval` to disambiguate the functionality.

Thanks again for the nice little library!

### CODE REVIEW

**Comment by blakewatters** [comment]
Another API change that I would propose making is to remove the `UILabel` category for calculating the lines of text in a label and move it into a C function like `NSArray *WBLinesOfTextInLabel(UILabel *label)`. Adding a method with as generic a name as `lines` to a class feels like an invitation for a conflict and I don't know that its going to be reused beyond the implementation within the notice view, so a private C function feels lighter weight.

**Comment by tciuro** [comment]
Blake, thanks so much for your hard work. I'm going to check the changes right away. Looking forward merging these fixes/additions. Cheers!

**Comment by tciuro** [comment]
Hey Blake, with all these changes I'm inclined to set the version to 3.0. It's not exactly an incremental change. Could you please set the version in the podspec file 3.0? I'd like to merge everything at once. Thanks a lot!

**Comment by blakewatters** [comment]
Hey Tito -

I have bumped the version to 3.0. I didn't tackle any changes in the README, so it will need to get revved once you merge.

**Comment by tciuro** [comment]
Cool! Thanks Blake. I'll prepare the README text to coalesce the major points that went into 3.0. Again, thanks for your effort! :-)

**Pull request merged**
