### PR TITLE
Add new `floating` (BOOL) property. (KVO + UIScrollView solution)

### PR DESCRIPTION
**Pull request by plu**
This property allows the `NoticeView` to be floating at the same position in a `UIScrollView`, while the user is scrolling. It's pretty much the same implementation as in the pull request #41, using KVO. It's just based upon the most recent HEAD of master, and includes some fix (leaked observers). There're also two new buttons in the example project to test it.

I've added this new property on purpose: Maybe there are `NoticeView` users out there who expect the `NoticeView` to be scrolling inside a `UIScrollView` instead of floating. Having the extra property will not break existing apps.

### CODE REVIEW

**Comment by tciuro** [comment]
Thanks Johannes!

**Comment by plu** [comment]
Thanks a lot for merging the pull request!

Do you have any plans on when to create the 3.0.6 tag? I'll take care of adding that to CocoaPods then.

**Comment by tciuro** [comment]
Done!

**Comment by plu** [comment]
Awesome! Thanks a lot :).

**Pull request merged**
