### PR TITLE
KVO UIScrollView contentOffset

### PR DESCRIPTION
**Pull request by Frugghi**
I merged your master and made the changes again, now automatically merge should work.

### CODE REVIEW

**Comment by Frugghi** [comment]
Mmm now there are duplicate commits, it's a problem?

(I need to learn how to use git correctly)

**Comment by plu** [comment]
I'm currently struggling with the same wish: Make the `NoticeView` stick on top of my table view while the user is scrolling. Instead of making the `NoticeView` handle it correctly, a much simpler solution is to add the `NoticeView` to another view that is not the `UIScrollView`: Just add it to `self.view.superview` instead of `self.view` (which is supposed to be a `UIScrollView`). Maybe this helps you too :).

``` objc
WBSuccessNoticeView *notice;
notice = [WBSuccessNoticeView successNoticeInView:self.view.superview
                                            title:@"You're offline, will submit later."];
[NSOperationQueue addNoticeView:notice filterDuplicates:YES];
```

**Comment by tciuro** [comment]
@Frugghi and @plu,

Is this issue solved now? Unfortunately I cannot find the time to verify this at the moment. Is it still an issue? Thanks for the help!

**Comment by Frugghi** [comment]
@plu 
My NoticeView fork handle it correctly!

Your solution works (only) if the scrollview and its superview have the same frame.

**Comment by plu** [comment]
@Frugghi you're right, my solution isn't flawless and it only works if the frame is the same. I could not test your fork though, it does not apply cleanly upon the current master anymore.
@tciuro it would be nice if `NoticeView` could handle scrolling and adjust the position while the user is scrolling, so it feels like the `NoticeView` is _sticking_ to its current position.

**Comment by tciuro** [comment]
@Frugghi Sorry, but I cannot merge the fix automatically:

```
tciuro$ git pull https://github.com/Frugghi/NoticeView.git master
remote: Counting objects: 51, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 36 (delta 30), reused 24 (delta 18)
Unpacking objects: 100% (36/36), done.
From https://github.com/Frugghi/NoticeView
 * branch            master     -> FETCH_HEAD
Auto-merging NoticeView/en.lproj/MainStoryboard.storyboard
CONFLICT (content): Merge conflict in NoticeView/en.lproj/MainStoryboard.storyboard
Auto-merging NoticeView/WBNoticeView/WBNoticeView.m
CONFLICT (content): Merge conflict in NoticeView/WBNoticeView/WBNoticeView.m
Auto-merging NoticeView/WBNoticeView/WBNoticeView.h
CONFLICT (content): Merge conflict in NoticeView/WBNoticeView/WBNoticeView.h
Automatic merge failed; fix conflicts and then commit the result.
tciuro$ 
```

Could you please revise the change and try once more? Many thanks!

**Pull request closed without merging**
